create_clock -name clk -period 6.66 [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_pixel[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_pixel[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports i_h_sync]
set_property PACKAGE_PIN G14 [get_ports {i_pixel[0]}]
set_property PACKAGE_PIN C20 [get_ports {i_pixel[1]}]
set_property PACKAGE_PIN B20 [get_ports {i_pixel[2]}]
set_property PACKAGE_PIN B19 [get_ports {i_pixel[3]}]
set_property PACKAGE_PIN A20 [get_ports {i_pixel[4]}]
set_property PACKAGE_PIN E17 [get_ports {i_pixel[5]}]
set_property PACKAGE_PIN D18 [get_ports {i_pixel[6]}]
set_property PACKAGE_PIN D19 [get_ports {i_pixel[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports i_v_sync]
set_property IOSTANDARD LVCMOS18 [get_ports o_v_sync]
set_property IOSTANDARD LVCMOS18 [get_ports o_h_sync]
set_property PACKAGE_PIN M17 [get_ports {o_pixel[7]}]
set_property PACKAGE_PIN M20 [get_ports {o_pixel[6]}]
set_property PACKAGE_PIN M19 [get_ports {o_pixel[5]}]
set_property PACKAGE_PIN F17 [get_ports {o_pixel[4]}]
set_property PACKAGE_PIN F16 [get_ports {o_pixel[3]}]
set_property PACKAGE_PIN E19 [get_ports {o_pixel[2]}]
set_property PACKAGE_PIN E18 [get_ports {o_pixel[1]}]
set_property PACKAGE_PIN D20 [get_ports {o_pixel[0]}]

set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN U12 [get_ports i_h_sync]
set_property PACKAGE_PIN U13 [get_ports i_v_sync]
set_property PACKAGE_PIN V13 [get_ports o_h_sync]
set_property PACKAGE_PIN V12 [get_ports o_v_sync]
set_property PACKAGE_PIN W13 [get_ports rst_n]


